In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.6,4.5,23.5],[13.42,54.65,42.66]])
print(b)

[[ 9.6   4.5  23.5 ]
 [13.42 54.65 42.66]]


In [4]:
#get dimension
a.ndim
# b.ndim

1

In [5]:
#get shape
b.shape

(2, 3)

In [6]:
# get type
a.dtype

dtype('int32')

In [7]:
# get size
a.itemsize

4

In [8]:
# get total size
a.nbytes

12

In [9]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
c[1,5]

np.int64(13)

In [11]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
c[:,3]

array([ 4, 11])

In [13]:
c[0,1:-1:2]

array([2, 4, 6])

In [14]:
c[1,5] = 22
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 22 14]]


In [15]:
c[:,4] = 3
print(c)

[[ 1  2  3  4  3  6  7]
 [ 8  9 10 11  3 22 14]]


In [16]:
c[:,3] = [66,13]
print(c)

[[ 1  2  3 66  3  6  7]
 [ 8  9 10 13  3 22 14]]


In [17]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [19]:
d[:,0,:] = [[11,12],[13,14]]
print(d)

[[[11 12]
  [ 3  4]]

 [[13 14]
  [ 7  8]]]


In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [23]:
np.full((3,4),30,dtype='float64')

array([[30., 30., 30., 30.],
       [30., 30., 30., 30.],
       [30., 30., 30., 30.]])

In [24]:
np.full_like(a,5)

array([5, 5, 5], dtype=int32)

In [25]:
np.random.rand(4,2)

array([[0.95174169, 0.65024007],
       [0.46333879, 0.92924565],
       [0.53433211, 0.24127914],
       [0.13163855, 0.97795939]])

In [26]:
np.random.random_sample(b.shape)

array([[0.41500146, 0.9222171 , 0.13970426],
       [0.2075362 , 0.4165458 , 0.50993796]])

In [27]:
np.random.randint(4,7,size=(4,4))
# 4 is start no, 7 is end (exclusive)

array([[6, 5, 4, 4],
       [5, 6, 5, 4],
       [4, 4, 5, 5],
       [4, 4, 5, 5]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr = np.array([[1,2,3,4,5]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [30]:
f = np.array([1,2,3])
g = f.copy()
g[0] = 5;
print(f)

[1 2 3]


In [31]:
h = np.array([1,2,3])
print(h)

[1 2 3]


In [32]:
i = np.array([4,5,6])
h+i

array([5, 7, 9])

In [33]:
h + 2

array([3, 4, 5])

In [34]:
h-2

array([-1,  0,  1])

In [35]:
h*2

array([2, 4, 6])

In [36]:
h/2

array([0.5, 1. , 1.5])

In [37]:
i**2

array([16, 25, 36])

In [38]:
np.sin(i)

array([-0.7568025 , -0.95892427, -0.2794155 ])

In [39]:
np.cos(i)

array([-0.65364362,  0.28366219,  0.96017029])

In [40]:
output = np.ones((5,5))
zero = np.zeros((3,3))
zero[1,1] = 9
output[1:-1,1:-1] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
ab = np.identity(3)
print(np.linalg.det(ab))

1.0


In [43]:
stats = np.array([[1,2,3],[4,5,6]])

In [44]:
np.min(stats)

np.int64(1)

In [45]:
np.max(stats,axis=1)

array([3, 6])

In [46]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [47]:
np.sum(stats,axis=1)

array([ 6, 15])

In [48]:
np.sum(stats)

np.int64(21)

In [49]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [51]:
v3 = np.ones((2,4))
v4 = np.zeros((2,2))
print(np.hstack((v3,v4)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [52]:
filetext = np.genfromtxt('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/numpy/data.txt',delimiter=',')
filetype = filetext.astype('int32')
print(filetext)

[[ 12.   3.  32.   5.   6.   7.   5.   4.]
 [  9.  65.  57.  46. 754. 757. 876.  47.]
 [ 46.   7.  65.   7.   7.  35.   7.  73.]]


In [53]:
filetext > 50

array([[False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True,  True,  True, False],
       [False, False,  True, False, False, False, False,  True]])

In [54]:
filetype[filetext>50]

array([ 65,  57, 754, 757, 876,  65,  73], dtype=int32)

In [55]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,6]]

array([2, 4, 7])

In [56]:
np.any(filetext > 50,axis=0)

array([False,  True,  True, False,  True,  True,  True,  True])

In [57]:
np.all(filetext > 50,axis=0)

array([False, False, False, False, False, False, False, False])

In [58]:
np.any(filetext > 50,axis=1)

array([False,  True,  True])

In [59]:
np.all(filetext > 50,axis=1)

array([False, False, False])

In [60]:
((filetext>50)&(filetext<100))

array([[False, False, False, False, False, False, False, False],
       [False,  True,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False,  True]])

In [61]:
(~((filetext>50)&(filetext<100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True, False]])

In [62]:
quiz = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,8,19,20],[21,22,23,24,25]])
print(quiz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17  8 19 20]
 [21 22 23 24 25]]


In [63]:
quiz[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [64]:
quiz[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [65]:
quiz[[0,3,4],3:]

array([[ 4,  5],
       [19, 20],
       [24, 25]])