In [74]:
import numpy as np

In [75]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [76]:
b = np.array([[9.6,4.5,23.5],[13.42,54.65,42.66]])
print(b)

[[ 9.6   4.5  23.5 ]
 [13.42 54.65 42.66]]


In [77]:
#get dimension
a.ndim
# b.ndim

1

In [78]:
#get shape
b.shape

(2, 3)

In [79]:
# get type
a.dtype

dtype('int32')

In [80]:
# get size
a.itemsize

4

In [81]:
# get total size
a.nbytes

12

In [82]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [83]:
c[1,5]

np.int64(13)

In [84]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
c[:,3]

array([ 4, 11])

In [86]:
c[0,1:-1:2]

array([2, 4, 6])

In [87]:
c[1,5] = 22
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 22 14]]


In [88]:
c[:,4] = 3
print(c)

[[ 1  2  3  4  3  6  7]
 [ 8  9 10 11  3 22 14]]


In [89]:
c[:,3] = [66,13]
print(c)

[[ 1  2  3 66  3  6  7]
 [ 8  9 10 13  3 22 14]]


In [90]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [91]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [92]:
d[:,0,:] = [[11,12],[13,14]]
print(d)

[[[11 12]
  [ 3  4]]

 [[13 14]
  [ 7  8]]]


In [93]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [94]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [96]:
np.full((3,4),30,dtype='float64')

array([[30., 30., 30., 30.],
       [30., 30., 30., 30.],
       [30., 30., 30., 30.]])

In [97]:
np.full_like(a,5)

array([5, 5, 5], dtype=int32)

In [98]:
np.random.rand(4,2)

array([[0.56667828, 0.91908041],
       [0.99399114, 0.08991814],
       [0.78622902, 0.30602757],
       [0.63453457, 0.10656328]])

In [99]:
np.random.random_sample(b.shape)

array([[0.41877281, 0.76734709, 0.01231645],
       [0.44680349, 0.18835698, 0.15013273]])

In [100]:
np.random.randint(4,7,size=(4,4))
# 4 is start no, 7 is end (exclusive)

array([[6, 5, 5, 5],
       [6, 5, 5, 5],
       [6, 5, 6, 4],
       [4, 5, 6, 5]])

In [101]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [102]:
arr = np.array([[1,2,3,4,5]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [103]:
f = np.array([1,2,3])
g = f.copy()
g[0] = 5;
print(f)

[1 2 3]


In [104]:
h = np.array([1,2,3])
print(h)

[1 2 3]


In [105]:
i = np.array([4,5,6])
h+i

array([5, 7, 9])

In [106]:
h + 2

array([3, 4, 5])

In [107]:
h-2

array([-1,  0,  1])

In [108]:
h*2

array([2, 4, 6])

In [109]:
h/2

array([0.5, 1. , 1.5])

In [110]:
i**2

array([16, 25, 36])

In [111]:
np.sin(i)

array([-0.7568025 , -0.95892427, -0.2794155 ])

In [112]:
np.cos(i)

array([-0.65364362,  0.28366219,  0.96017029])

In [113]:
output = np.ones((5,5))
zero = np.zeros((3,3))
zero[1,1] = 9
output[1:-1,1:-1] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [114]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [115]:
ab = np.identity(3)
print(np.linalg.det(ab))

1.0


In [116]:
stats = np.array([[1,2,3],[4,5,6]])

In [117]:
np.min(stats)

np.int64(1)

In [118]:
np.max(stats,axis=1)

array([3, 6])

In [119]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [120]:
np.sum(stats,axis=1)

array([ 6, 15])

In [121]:
np.sum(stats)

np.int64(21)

In [122]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [123]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [124]:
v3 = np.ones((2,4))
v4 = np.zeros((2,2))
print(np.hstack((v3,v4)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [125]:
filetext = np.genfromtxt('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/numpy/data.txt',delimiter=',')
filetype = filetext.astype('int32')
print(filetext)

[[ 12.   3.  32.   5.   6.   7.   5.   4.]
 [  9.  65.  57.  46. 754. 757. 876.  47.]
 [ 46.   7.  65.   7.   7.  35.   7.  73.]]


In [126]:
filetext > 50

array([[False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True,  True,  True, False],
       [False, False,  True, False, False, False, False,  True]])

In [127]:
filetype[filetext>50]

array([ 65,  57, 754, 757, 876,  65,  73], dtype=int32)

In [128]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,6]]

array([2, 4, 7])

In [129]:
np.any(filetext > 50,axis=0)

array([False,  True,  True, False,  True,  True,  True,  True])

In [130]:
np.all(filetext > 50,axis=0)

array([False, False, False, False, False, False, False, False])

In [131]:
np.any(filetext > 50,axis=1)

array([False,  True,  True])

In [132]:
np.all(filetext > 50,axis=1)

array([False, False, False])

In [133]:
((filetext>50)&(filetext<100))

array([[False, False, False, False, False, False, False, False],
       [False,  True,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False,  True]])

In [134]:
(~((filetext>50)&(filetext<100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True, False]])

In [135]:
quiz = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,8,19,20],[21,22,23,24,25]])
print(quiz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17  8 19 20]
 [21 22 23 24 25]]


In [136]:
quiz[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [138]:
quiz[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [141]:
quiz[[0,3,4],3:]

array([[ 4,  5],
       [19, 20],
       [24, 25]])